### ISSUE TITLE
Downloading comments progress bar goes beyond 100%

### ISSUE THREAD

**Issue by faizollah** [sachin-bisht/YouTube-Sentiment-Analysis#3]
Hi,

I used the code to download comments. It was ok couple of days ago. Today, the progress bar for downloading comments goes over 100% and doesn't stop. Can you help please?

Thanks

**Comment by sachin-bisht** [comment]
Check comment_extract.py and progress_bar.py file. The problem should be there. Some corner cases might be missing.
